<?php
namespace Tests\Feature\Integrations;

use App\Course;
use App\Quiz;
use Tests\Concerns\CourseConcerns;
use Tests\Concerns\QuizConcerns;
use Tests\TestCase;

class QuizTest extends TestCase
{
    use QuizConcerns;
    use CourseConcerns;

    /** @var Course */
    public $course;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->createApplication();

        $this->course = $this->creteCourse();
    }

    /** @test */
    public function it_creates_working_quiz_with_questions()
    {
        // given

        // when
        $quiz = $this->createQuiz($this->course);

        // then
        $this->assertTrue($quiz instanceof Quiz);
        $this->assertTrue($quiz->questions->count() > 0);
        $this->assertEquals(3, $quiz->questions->count());
    }


}