<?php
namespace Tests\Feature\Integrations;

use App\Course;
use App\Quiz;
use Tests\Concerns\CourseConcerns;
use Tests\Concerns\QuizConcerns;
use Tests\TestCase;

class QuizTest extends TestCase
{
    use QuizConcerns;
    use CourseConcerns;

    /** @var Course */
    public $course;

    /** @var Quiz */
    public $quiz;

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->createApplication();

        $this->course = $this->creteCourse();
        $this->quiz = $this->createQuiz($this->course);
    }

    /** @test */
    public function it_creates_working_quiz_with_questions()
    {
        // given
        // Setup

        // when

        // then
        $this->assertTrue($this->quiz instanceof Quiz);
        $this->assertTrue($this->quiz->questions->count() > 0);
        $this->assertEquals(3, $this->quiz->questions->count());
    }


}