name: Test and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
#  laravel-tests:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Copy .env
#        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 7.2
#          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
#          coverage: none
#      - name: Install Dependencies
#        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
#      - name: Generate key
#        run: php artisan key:generate
#      - name: Directory Permissions
#        run: chmod -R 777 storage bootstrap/cache
#      - name: Create Database
#        run: |
#          mkdir -p database
#          touch database/database.sqlite
#      - name: Run migrations
#        env:
#          DB_CONNECTION: sqlite
#          DB_DATABASE: database/database.sqlite
#        run: php artisan migrate --force
#      - name: Execute tests (Unit and Feature tests) via PHPUnit
#        env:
#          DB_CONNECTION: sqlite
#          DB_DATABASE: database/database.sqlite
#        run: vendor/bin/phpunit

  build:
#    needs: [ laravel-tests ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Deploy iNauka
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET_INAUKA }}
          EXCLUDE: "/node_modules/, /.idea/, /.git/, /vendor/, /.github/"
      - name: Creating .env file should go here
        run: echo "Creating env file..."
      - name: Composer and migrations
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USER }}@${{ secrets.HOST }}
          privateKey: ${{ secrets.KEY }}
          command: |
            cd ${{ secrets.TARGET_INAUKA }}
            ln -s public public_html
            ln -s public private_html
            php74 composer.phar install
            php74 artisan migrate --force
            php74 artisan cache:clear
            php74 artisan view:cache
            php74 artisan config:cache
            php74 artisan storage:link

      - name: Deploy projekt30
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET_PROJEKT30 }}
          EXCLUDE: "/node_modules/, /.idea/, /.git/, /vendor/, /.github/"
      - name: Creating .env file should go here
        run: echo "Creating env file..."
      - name: Composer and migrations
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USER }}@${{ secrets.HOST }}
          privateKey: ${{ secrets.KEY }}
          command: |
            cd ${{ secrets.TARGET_PROJEKT30 }}
            ln -s public public_html
            ln -s public private_html
            php74 artisan migrate --force
            php74 artisan cache:clear
            php74 artisan view:cache
            php74 artisan config:cache
            php74 artisan storage:link

      - name: Deploy IS
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          TARGET: ${{ secrets.TARGET_IS }}
          EXCLUDE: "/node_modules/, /.idea/, /.git/, /vendor/, /.github/"
      - name: Creating .env file should go here
        run: echo "Creating env file..."
      - name: Composer and migrations
        uses: JimCronqvist/action-ssh@master
        with:
          hosts: ${{ secrets.USER }}@${{ secrets.HOST }}
          privateKey: ${{ secrets.KEY }}
          command: |
            cd ${{ secrets.TARGET_IS }}
            ln -s public public_html
            ln -s public private_html
            php74 artisan migrate --force
            php74 artisan cache:clear
            php74 artisan view:cache
            php74 artisan config:cache
            php74 artisan storage:link


